apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
spec:
  authentication:
    type: tls
  authorization:
    acls:
    {{- range $topicName := .Values.kafka.producerTopics }}
      - operations:
          - Write
        resource:
          type: topic
          name: {{ $topicName }}
    {{- end }}
    {{- range $topicName := .Values.kafka.consumerTopics }}
      - operations:
          - Read
        resource:
          type: topic
          name: {{ $topicName }}
    {{- end }}
      - resource:
          type: group
          name: {{ .Values.nameOverride }}
          patternType: literal
        operations:
          - Read
        host: "*"
    type: simple
